title: douglasjam
description: Um rascunho do que acho sei
author: Douglas J.A.M
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
base_url:
highlighter: rouge
excerpt_separator: <!--more-->
paginate: 5
include: ['_pages']
sass:
  style: :expanded
urls:
  - text: github
    url: https://github.com/douglasjam
  - text: linkedin
    url: https://www.linkedin.com/in/douglasjam
  - text: instagram
    url: https://www.instagram.com/douglasjam
picture:
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5, 2]
      source_large:
        media: "(min-width: 480px)"
        width: "252"
      source_default:
        width: "480"
    thumb_index:
      ppi: [1, 1.5, 2]
      source_default:
        width: "150"
        height: "150"
gems :
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-picture-tag

# todo's
# multilingual support
# https://github.com/screeninteraction/jekyll-multiple-languages-plugin
#excerpt
#http://www.remotesynthesis.com/general/2015/10/02/advanced-jekyll-templates/
#https://02dc74ce3e31e56a52ebcc845dca58e87283aabe.googledrive.com/host/0Bxbofwq0kd4ReUt2YWVOYmt3WVU/
#https://github.com/robwierzbowski/jekyll-image-tag
#{% image_tag src=page.thumbnail width="200" %}
