name: douglasjam
markdown: redcarpet
highlighter: rouge
about: I am an independent developer from the sunny UK. I dabble in Ruby, play in C and I'm an avid systems administrator.
urls:
  - text: github
    url: https://github.com/douglasjam
  - text: linkedin
    url: https://www.linkedin.com/in/douglasjam
  - text: instagram
    url: https://www.instagram.com/douglasjam

# todo's
# multilingual support
# https://github.com/screeninteraction/jekyll-multiple-languages-plugin