title: Douglas Moreira
description: Personal Blog


author: Douglas Moreira
gravatar: https://www.gravatar.com/avatar/5d554af07043c1e196dc6eaa1b8b0aa5?size=192

paginate: 5

responsive_image:
  template: _includes/srcset.html
  sizes:
    - width: 80
    - width: 320
    - width: 480
    - width: 800

plugins:
  - jekyll-paginate
  - jekyll-responsive-image
  - jekyll-postcss
