title: douglasjam
description: Um rascunho sobre as coisas que faco, dentre elas, computacao, eletronica, viagens e coisas do dia a dia.
url: http://www.douglasjam.com.br
markdown: kramdown
highlighter: rouge
paginate: 10
urls:
  - text: github
    url: https://github.com/douglasjam
  - text: linkedin
    url: https://www.linkedin.com/in/douglasjam
  - text: instagram
    url: https://www.instagram.com/douglasjam

# todo's
# multilingual support
# https://github.com/screeninteraction/jekyll-multiple-languages-plugin
#excerpt