title: douglasjam
description: Um rascunho sobre as coisas que faco, dentre elas, computacao, eletronica, viagens e coisas do dia a dia.
url: 
markdown: kramdown
highlighter: rouge
author: Douglas J.A.M
paginate: 5
urls:
  - text: github
    url: https://github.com/douglasjam
  - text: linkedin
    url: https://www.linkedin.com/in/douglasjam
  - text: instagram
    url: https://www.instagram.com/douglasjam

# todo's
# multilingual support
# https://github.com/screeninteraction/jekyll-multiple-languages-plugin
#excerpt
#http://www.remotesynthesis.com/general/2015/10/02/advanced-jekyll-templates/
#https://02dc74ce3e31e56a52ebcc845dca58e87283aabe.googledrive.com/host/0Bxbofwq0kd4ReUt2YWVOYmt3WVU/